version: '3.6'

services:
  web:
    build: ./web
    command: python /code/manage.py migrate --noinput
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
      - ./common/:/code/common
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=x^)h7pf=if_x+c8u*ahf$ne#yo1(7@kv#ajj$c7tukkalk$c#l
      - KAFKA_BROKER_URL=kafka:9092
      - UPLOAD_TOPIC=UPLOADS
  slicer:
    build: ./slicer
    volumes:
      - ./slicer:/code
      - ./common:/code/common
      - ./web/uploads:/code/uploads
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - UPLOAD_TOPIC=UPLOADS
    depends_on:
      - ffmpeg
  ffmpeg:
    image: jrottenberg/ffmpeg:3.3
networks:
  default:
    external:
      name: kafka-network